sculpin_pagination:
    max_per_page: 50

sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
    talks:
        permalink: talk/:slug_title/
        singular_name: talk
        type: path
        path: _talks
        enabled: true
        layout: talk
