# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: gabriela.IO
subtitle: ideas in and out!
url: http://gabriela.io
blog_url: "http://gabriela.io/blog"
author:
  pic: "http://gabriela.io/img/gabi.jpg"
  name: "Gabriela D'Ávila"
  title: "Software Engineer, Lego fan."
  lego: 24084

social:
  0:
    name: "Github"
    link: "http://www.github.com/gabidavila"
    icon: "github"
  1:
    name: "Twitter"
    link: "http://twitter.com/gabidavila"
    icon: "twitter"
  2:
    name: "Linkedin"
    link: "http://linkedin.com/in/gabrieladavila/"
    icon: "linkedin"
  3:
    name: "Google Plus"
    link: "http://plus.google.com/+GabrielaDÁvila00"
    icon: "google-plus"

google_analytics_tracking_id: "UA-54774199-1"

blogroll:
  0:
    name: "dev-human"
    url: "http://www.dev-human"
  1:
    name: "weDiversifi"
    url: "http://wwww.wediversi.fi"
  2:
    name: "PHP Women"
    url: "http://phpomen.com"

default_date_format: M d, Y

authors:
 gabriela:
      name: "Gabriela D'Ávila"
      url: http://gabriela.io